[theme]
primaryColor = "#167D8D"
backgroundColor = "#F7F9FC"
secondaryBackgroundColor = "#EDF2F7"
textColor = "#182B49"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
address = "127.0.0.1"
headless = true
